53 feather file conversion support
conbench/datalogistik pull request #107
Opened 2022-10-10 14:49 UTC by joosthooz

Fixes #53 
Adds support for the feather file support, although conversion to compressed feather does not work because this is not supported by pyarrow.dataset. In addition, there is no API to find the compression used in an existing file (like for parquet), so we rely on the user to set this property in the metadata.

2022-10-11 14:02 UTC, jonkeane commented on datalogistik/dataset.py
> +
We might need to upstream adding this option to pyarrow — we will need this compression available in order to use datalogistik. This _is_ available from R (cf https://arrow.apache.org/docs/r/reference/write_dataset.html `write_dataset(..., codec = Codec$create("lz4"))` works for example.

https://github.com/apache/arrow/blob/3d7f2f22a0fc441a41b8fa971e11c0f4290ebb24/r/src/dataset.cpp#L257-L264 is the cpp that wires it up

2022-10-11 14:51 UTC, jonkeane commented on tests/test_datalogistik.py
> +        monkeypatch.setenv("DATALOGISTIK_CACHE", tmpdspath)
Could we set this at the top of the file like we do at https://github.com/conbench/datalogistik/blob/be1f24c99e8d78ac4af9d3490099a3a5e54679b4/tests/test_dataset.py#L111-L113 ?

2022-10-12 09:52 UTC, joosthooz commented
Created JIRA about the absence of compression support in pyarrow.dataset.ipc: https://issues.apache.org/jira/browse/ARROW-17991

2022-10-12 10:20 UTC, joosthooz commented on README.rst
> +    ``parquet``, ``csv``, ``feather``.
We need Arrow 10.0 for that (https://github.com/apache/arrow/pull/13677).
I pushed the changes needed in datalogistik here https://github.com/conbench/datalogistik/pull/109

2022-10-12 10:23 UTC, joosthooz commented on tests/test_datalogistik.py
> +        monkeypatch.setenv("DATALOGISTIK_CACHE", tmpdspath)
We cannot, because the tempfile only exists in this context. Is this a bad pattern? Should I do a cleanup like here https://github.com/conbench/datalogistik/blob/be1f24c99e8d78ac4af9d3490099a3a5e54679b4/tests/test_datalogistik.py#L338 ?

2022-10-17 15:26 UTC, austin3dickey commented on tests/test_datalogistik.py
> +        monkeypatch.setenv("DATALOGISTIK_CACHE", tmpdspath)
I think the way it is now is fine. It's something that won't be re-used across different tests

2022-10-19 09:25 UTC, joosthooz commented
At first, I figured we'd just use the normal ipc writer for now, but now you mention the nightlies, I think that might be a better idea. Because there could be more stuff we need that we add to Arrow ourselves.

2022-10-20 13:17 UTC, jonkeane commented
Would you mind setting up the dependency setup to pull a nightly for arrow in this PR + take out the stops that prevent compression from being used?

2022-10-21 11:32 UTC, joosthooz commented
Done. also merged #109 into this, so will close it.

2022-10-24 11:41 UTC, joosthooz commented
Now, pyarrow nightlies are installed for the test-wheel step. But for pipx, I had to add the flags (most notably `--pre`) needed to install pyarrow nightlies to the pipx command to install datalogistik, because otherwise a separate environment would be created. But I guess that means that for the other dependencies it might also install non-stable packages.

2022-10-24 20:34 UTC, jonkeane requested changes
Looking good, a few small(ish) changes we need to make, but once those are made  I tink we're ready to merge + try this in arrowbench

2022-10-24 20:34 UTC, jonkeane commented on .github/workflows/actions.yml
> +          ${{ matrix.installer }} install --pip-args "--extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre" '${{ matrix.installee }}'
```suggestion
          ${{ matrix.installer }} install --pip-args "--extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre=pyarrow" '${{ matrix.installee }}'
```

Does this work to restrict pyarrow to be the only prerelease allowed?

2022-10-24 20:34 UTC, jonkeane commented on datalogistik/dataset.py
> -            util.set_readonly_recurse(output_file)
I'm surprised this line wasn't erroring before?

2022-10-24 20:34 UTC, jonkeane commented on datalogistik/dataset_search.py
>      # when we support .arrow, those likely should be first, then parquet, et c.
We should rephrase this comment now that we support arrow files

2022-10-24 20:34 UTC, jonkeane commented on tests/test_datalogistik.py
> +    "'x': 'timestamp[us]'}"
Can you explain more about this change? It seems a bit unrelated, was it needed for the tests to pass or something?

2022-10-24 20:34 UTC, jonkeane commented on tests/test_datalogistik.py
> +# )
Can we remove this commented code?

2022-10-25 09:16 UTC, joosthooz commented on tests/test_datalogistik.py
> +    "'x': 'timestamp[us]'}"
IIRC, one of the formats (can't remember which) didn't support ms, or otherwise had a problem with round-tripping it to the other formats.

2022-10-25 09:18 UTC, joosthooz commented on tests/test_datalogistik.py
> +# )
Done

2022-10-25 09:18 UTC, joosthooz commented on datalogistik/dataset_search.py
>      # when we support .arrow, those likely should be first, then parquet, et c.
Done

2022-10-25 09:18 UTC, joosthooz commented on datalogistik/dataset.py
> +            dataset_read_format = "arrow"
Absolutely!

2022-10-25 09:19 UTC, joosthooz commented on .github/workflows/actions.yml
> +          ${{ matrix.installer }} install --pip-args "--extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre" '${{ matrix.installee }}'
I tried a different approach; instead of the general `--pre` (removed), I added a dev version as minimum (`'pyarrow>=10.0.0dev497'`).

2022-10-25 09:51 UTC, joosthooz commented on .github/workflows/actions.yml
> +          ${{ matrix.installer }} install --pip-args "--extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary --pre" '${{ matrix.installee }}'
After a few tries, it finally works, by just adding the nightly repo to the install commands and then the new minimum version sorts it out automatically.

2022-10-26 20:26 UTC, jonkeane commented on .github/workflows/actions.yml
> +          ${{ matrix.installer }} install --pip-args "--extra-index-url https://pypi.fury.io/arrow-nightlies/ --prefer-binary" '${{ matrix.installee }}'
We should add the extra index urls to the readme too

2022-10-26 21:18 UTC, jonkeane approved these changes
I tested this with arrowbench and it works 🎉 . One comment about adding the pipx instructions to the readme (and looks like there's a conflict too)

2022-10-27 08:40 UTC, merged