Added ndjson support
conbench/datalogistik pull request #116
Opened 2022-11-01 14:09 UTC by joosthooz

2022-11-01 16:52 UTC, joosthooz commented
This is WIP; there seems to be something wrong when converting _from_ ndjson to the other formats.

2022-11-01 19:15 UTC, joosthooz commented
Now it works. But I still want to make some improvements to the conversion tests.

2022-11-01 20:56 UTC, joosthooz commented
I made some improvements that should make the test code a bit more clear and remove a lot of duplication from the schema (all kinds of variants for the different format, each with a subset of suppoted types).

2022-11-02 16:56 UTC, jonkeane requested changes
Looking good. I made two comments where will likely be pretty big changes (at least lines-changed wise). The factoring into a function our writting code is something I was already close to suggesting when we added the arrow format, but looking at how many levels of indentation we have there: I suspect now is the time for us to factor that out into separate functions

2022-11-02 16:56 UTC, jonkeane commented on datalogistik/dataset.py
> +                            writer.writerow(row)
I wonder if this is getting complicated enough that it makes sense to pull it out into a new function?

2022-11-02 16:56 UTC, jonkeane commented on datalogistik/dataset.py
> +        if self.format == "ndjson":  # not supported by pyarrow.dataset
It might be nice to expand on this comment a little bit too, explaining that we use a table + will pull into memory, etc.

2022-11-02 16:56 UTC, jonkeane commented on tests/test_datalogistik.py
> +        )
While we're in here, would it be possible to name the columns with monikers that are close to the types that they are, so it's easier to read this test as "ah, if it's a csv I don't support types: int32, float128, etc."?

2022-11-07 21:12 UTC, jonkeane commented
I haven't had a chance to dig into this more deeply, but I'm getting a funny error on linux only: https://github.com/voltrondata-labs/arrowbench/actions/runs/3395986451/jobs/5646533349#step:10:272

2022-11-08 10:08 UTC, joosthooz commented
It seems the memory usage was too high, so the program would get killed when convering a large dataset like fanniemae. This last change should help.

2022-11-08 21:55 UTC, jonkeane requested changes

2022-11-08 21:55 UTC, jonkeane commented on datalogistik/dataset.py
> +        if self.format == "ndjson":  # not supported by pyarrow.dataset
Thoughts about ^^^?

2022-11-08 21:55 UTC, jonkeane commented on tests/test_datalogistik.py
> +        )
I still think that ^^^ would be a good idea — is that too much work for this PR?

2022-11-08 21:56 UTC, jonkeane commented on datalogistik/dataset.py
> +                            writer.writerow(row)
Thoughts on this? I think factoring this stuff out into separate functions would really improve readability + testability

2022-11-08 21:57 UTC, jonkeane commented
I just rebased this to get the new env var for not-changing permissions, testing over an arrowbench again

2022-11-09 16:49 UTC, joosthooz commented on datalogistik/dataset.py
> +                            writer.writerow(row)
Absolutely, I gave it a try. There is some uglyness because we need to pass the source format and file path in case we're dealing with ndjson.
Also, the writing function is a member function, which should be called on the `new_dataset`, which could a bit confusing. Maybe I should pass a complete source Dataset instead. What do you think?

2022-11-09 16:50 UTC, joosthooz commented on datalogistik/dataset.py
> +        if self.format == "ndjson":  # not supported by pyarrow.dataset
Definitely good to expand this comment a bit, done

2022-11-09 16:50 UTC, joosthooz commented on tests/test_datalogistik.py
> +        )
I converted the names to basically the type name, I think this makes it much more clear!

2022-11-29 20:52 UTC, merged