Added cache bypass option
conbench/datalogistik pull request #31
Opened 2022-08-04 11:26 UTC by joosthooz

PR to address #10

2022-08-04 18:58 UTC, austin3dickey requested changes
nice, looks good! are you going to do the third subtask in this PR?

2022-08-04 18:58 UTC, austin3dickey commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Could you add this to the .gitignore please?

2022-08-04 18:58 UTC, austin3dickey commented on datalogistik/cli.py
> +    )
Could you add all these new options to the README?

2022-08-04 19:00 UTC, austin3dickey commented
To fix the build, you'll have to fix the CI yml [here](https://github.com/conbench/datalogistik/blob/main/.github/workflows/actions.yml#L123) and [here](https://github.com/conbench/datalogistik/blob/main/.github/workflows/actions.yml#L148) with the new CLI structure

2022-08-05 12:54 UTC, joosthooz commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Sorry, this should not have been committed! I just removed it, it seems weird to have such a tool-specific item in the .gitignore

2022-08-05 12:54 UTC, joosthooz commented on datalogistik/cli.py
> +    )
Added in [1abcacc](https://github.com/conbench/datalogistik/pull/31/commits/1abcacc132406bd485f5e2643e41110b9a7d482b)

2022-08-05 12:55 UTC, joosthooz commented
> nice, looks good! are you going to do the third subtask in this PR?
No, I created a new issue for that: #33

2022-08-05 14:58 UTC, austin3dickey requested changes
nice, a few more things

2022-08-05 14:58 UTC, austin3dickey commented on datalogistik/cli.py
> +        "--bypass-cache",
oh could you please add this to the README too?

2022-08-05 14:58 UTC, austin3dickey commented on README.rst
> +    datalogistik generate <generate|cache>
Just a nitpick

```suggestion
    datalogistik <generate|cache>
```

2022-08-05 14:58 UTC, austin3dickey commented on datalogistik/util.py
> +                    metadata = json.load(open(metadata_file))
Would you mind using a context manager here so the `metadata_file` gets closed again? I don't want the open file to cause any headaches later

2022-08-05 14:58 UTC, austin3dickey commented on datalogistik/util.py
> +                    metadata = json.load(open(metadata_file))
And same down below where `open()` is used again

2022-08-05 14:58 UTC, austin3dickey commented on datalogistik/util.py
> +        walking_path = pathlib.Path(path).parent
I wonder if this chunk of code would be better as another util function? It's complex enough that separating its concerns would probably be easier to understand, and then you could call the new function both here and above

2022-08-09 10:07 UTC, joosthooz commented on datalogistik/util.py
> +        walking_path = pathlib.Path(path).parent
Done in [dc3d499](https://github.com/conbench/datalogistik/pull/31/commits/dc3d499e816f52ffe7cd5f62dd38ed77fe9d324b)

2022-08-09 10:08 UTC, joosthooz commented on datalogistik/util.py
> +                    metadata = json.load(open(metadata_file))
Done in [da57570](https://github.com/conbench/datalogistik/pull/31/commits/da5757024f938e9d280475c99b578db8af2f037d)

2022-08-09 10:08 UTC, joosthooz commented on README.rst
> +    datalogistik generate <generate|cache>
Done, thanks for catching

2022-08-09 10:08 UTC, joosthooz commented on datalogistik/cli.py
> +        "--bypass-cache",
Done in [ae4861e](https://github.com/conbench/datalogistik/pull/31/commits/ae4861e13f4beecd5f21eedaf320b2b7e90018fb)

2022-08-09 10:09 UTC, joosthooz commented
Alright, I think I took care of the items, let me know what you think

2022-08-09 15:40 UTC, austin3dickey approved these changes
looks good!

2022-08-10 07:16 UTC, merged