validate file integrity
conbench/datalogistik pull request #34
Opened 2022-08-05 15:06 UTC by joosthooz

Addressing #1 

Added a `validate` command that can:
- [x] Verify the integrity of a dataset given by path
- [x] Verify the integrity of all the entries in the cache

2022-08-08 14:39 UTC, austin3dickey commented
I'll review this once we merge #31 ; the diff is a little confusing otherwise

2022-08-10 18:36 UTC, austin3dickey requested changes

2022-08-10 18:36 UTC, austin3dickey commented on .github/workflows/actions.yml
> +  test-download-convert-p2c-without-repo:
This new section feels a little redundant to me. I should have put more comments in this file, but what I was thinking for the CI strategy was:
- `lint`, `check-copyright`: self-explanatory
- `unit-tests`: test as much behavior of this package as possible, without calling the CLI
- `build-wheel -> test-convert-without-repo`: a simple integration test of the CLI without cloning the repo, in order to test that that workflow works
- `test-tpc-integration`: an integration test of TPC-H and TPC-DS because they're complicated and need additional setup than we could provide in `unit-tests`

If you want to test that the conversion works, I'd say your unit tests are good without this new section in this file. But if you wanted to be extra sure, you could also change line 123 to "csv" instead of "parquet". I don't think we need another whole step though.

2022-08-10 18:36 UTC, austin3dickey commented on datalogistik/cli.py
> +    valid_parser = sub_parsers.add_parser("validate")
Could you please add documentation to the README? 🙂

2022-08-10 18:36 UTC, austin3dickey commented on datalogistik/util.py
> +        orig_file_listing = json.load(open(metadata_file)).get("files")
Could you please switch to the contextmanager `with open()` pattern here?

2022-08-10 18:36 UTC, austin3dickey commented on tests/test_datalogistik.py
> +def test_convert_dataset_parquet_to_csv():
Thanks for this test! Could you add a test that the validation functionality works?

2022-08-10 19:33 UTC, alistaire47 approved these changes
Looks good! A few comments to highlight some landmines in data validation that I've discovered the hard way to be aware of as you move forward

2022-08-10 19:33 UTC, alistaire47 commented on datalogistik/util.py
>          co = csv.ConvertOptions()
If the source of truth is in csv which then gets converted on to parquet and whatever, these options can have a non-trivial impact on what gets written back out to other formats. [In benchmarks](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_sources.py#L329-L354) I did a bit to lock it down, though I'd still hesitate to call it robust.

And for writing parquet [you may need to set `coerce_timestamps`](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_sources.py#L432) for consistent timestamp precision depending on what parquet version you're using.

2022-08-10 19:33 UTC, alistaire47 commented on repo.json
> +    "tables": [{"table" : "fanniemae_2016Q4.csv", "schema" : {
[Here's a better schema for fanniemae](https://github.com/voltrondata-labs/benchmarks/blob/main/benchmarks/_sources.py#L54-L98) whenever you want it

2022-08-11 09:44 UTC, joosthooz commented on datalogistik/util.py
> +def validate(path):
1) Thanks for spotting this! I will take care of this.
2) Yes, also individual files will be placed in a directory, also because there will always be a metadata file added. The presence of that metadata file (and the "files" entry in it) will be the factor that determines whether the dataset seems valid (if the program finds a directory without it, it will delete the directory).
3) I don't check them because if the file size is different (so the files are not identical), you can bet your butt that the checksums are also different. But I can add a size check before the checksum check

2022-08-11 09:49 UTC, joosthooz commented on datalogistik/util.py
>          co = csv.ConvertOptions()
Thanks, I'm actually struggling with these options because the schema detection in pyarrow.dataset is not good enough for the test datasets (fanniemae and nyctaxi). Passing the names would already help a bit but will not solve problems with the types of the schema: dataset detects the schema from the first x bytes of data (I think 1MB). So if there is a different value somewhere later on, it results in an error.
In the end a real solution would be to add the schema into the repo file and convert it to a pyarrow schema and pass it to the call creating the dataset. That's for #36 .

2022-08-11 09:50 UTC, joosthooz commented on repo.json
> +    "tables": [{"table" : "fanniemae_2016Q4.csv", "schema" : {
This is awesome, I'm going to add it right away

2022-08-11 11:23 UTC, joosthooz commented on repo.json
> +    "tables": [{"table" : "fanniemae_2016Q4.csv", "schema" : {
[d3e9d58](https://github.com/conbench/datalogistik/pull/34/commits/d3e9d5827d019a733e6efb5b262e0012795182a7)

2022-08-11 11:23 UTC, joosthooz commented on tests/test_datalogistik.py
> +def test_convert_dataset_parquet_to_csv():
Done in [88c8faf](https://github.com/conbench/datalogistik/pull/34/commits/88c8fafcaa550b85c462d0f61db1ac46dca3212f)

2022-08-11 11:24 UTC, joosthooz commented on datalogistik/util.py
> +        orig_file_listing = json.load(open(metadata_file)).get("files")
Done, also for 1 spot in the unit tests

2022-08-11 11:24 UTC, joosthooz commented on datalogistik/cli.py
> +    valid_parser = sub_parsers.add_parser("validate")
Yes! I Forgot (again), added

2022-08-11 11:25 UTC, joosthooz commented on .github/workflows/actions.yml
> +  test-download-convert-p2c-without-repo:
I understand, and removed the new test! Also changed output type to csv, to include a conversion. Maybe I'll add some more commands in this test, just so it hits most of the code

2022-08-11 14:08 UTC, joosthooz commented on datalogistik/util.py
> +def validate(path):
The deduplication is done

2022-08-11 14:28 UTC, joosthooz commented on datalogistik/util.py
> +def validate(path):
Ok I looked at the integrity check code again, and it does check both file size and checksum, because it just checks the whole file listing array item (containing file path, size, and md5). This check is performed 1) after downloading and decompressing a dataset, but only in case there is a file listing for it in the repo file, and 2) at user request (either for all the entries in the cache, or for a given path)

2022-08-11 14:33 UTC, alistaire47 commented on datalogistik/util.py
>          co = csv.ConvertOptions()
Yep, it's almost necessary to specify a schema when the original form is CSV/delimited; I ran into lots of issues with coerced nulls and null-type columns that caused downstream issues in addition to the obvious type differences

2022-08-11 14:51 UTC, alistaire47 commented on datalogistik/util.py
> +def validate(path):
Cool, size/checksum checks on the downloads should be pretty safe. Sizes get dicier for converted versions (e.g. a parquet/snappy/1e6 chunk size version of csv/gzip original) because they depend on all the reading and writing options, schema, and behavior, so any changes, deliberate or in defaults or behavior, cause failures. Less of an issue if deps are pinned, but I think the default parquet version is in the midst of changing, so choice of pin may be important

2022-08-12 07:43 UTC, joosthooz commented on datalogistik/util.py
> +def validate(path):
Yes, checking generated/converted datasets will be very difficult. We would need to extract only the pure contents and have a checksum for that in the repo file too. That's probably a bit outside the scope of this tool.

2022-08-12 09:10 UTC, joosthooz commented on datalogistik/util.py
>          co = csv.ConvertOptions()
I'm looking into coerce_timestamps, but `pyarrow.dataset` does not have en equivalent option.

2022-08-15 09:41 UTC, jonkeane commented on datalogistik/util.py
> +def validate(path):
Yeah, agreed that the derived datasets is probably more complicated than it's worth (certainly for now possible forever). It also should be _relatively_ quick to re-generate the derived datasets anyway, such that if we're having issues we can prune the cache and then everything should be fine.

2022-08-15 09:44 UTC, jonkeane commented
Thanks for this! I haven't dug in too deeply, but I do wonder if we even need the ad-hoc verification command to be surfaced at all. In normal operations I would expect this to run after a download (which it is already), and that's probably about it. 

It's nice to have the ability to do this adhoc, but I wonder if it's adding more user interface than we really need to at this point?

2022-08-15 15:22 UTC, joosthooz commented
You may be right. I added it because some people might want to do read and writes to a dataset, but maybe that doesn't make sense and people should just re-instantiate in that case. If the dataset is in the cache that would be comparable to verifying. I'm ok with removing the command. Maybe we can just merge cache cleaning and verification into 1 option that does both?

2022-08-16 15:08 UTC, joosthooz commented
There is now no longer a validate subcommand, instead there is a cache --validate command that verifies file integrity of all the cache entries. Invalid entries are pruned.

2022-08-16 15:58 UTC, jonkeane reviewed
A few small comments and one big one: 

I thought the last time I looked at this, we had code that would validate the single source of data after it had been downloaded. But I'm struggling to find that again. Did we remove that? IMHO, validating after downloading is probably the only thing we want to expose right now (and do it unconditionally). Most datasets should be relatively easy to download such that if someone is concerned about their cache being corrupt, we should make it easy for them to delete everything for a datasource and start from scratch (downloading it).

Thoughts?

2022-08-16 15:58 UTC, jonkeane commented on README.rst
> +    datalogistik <generate|cache|validate>
```suggestion
    datalogistik <generate|cache>
```

If we only have an argument now we should do this, yeah?

2022-08-16 15:58 UTC, jonkeane commented on datalogistik/cli.py
> +    )
If this auto-prunes, maybe we should call this `--prune-invalid` or something? That way it's clear what it's going to do if there's something that is invalid?

2022-08-16 20:05 UTC, austin3dickey commented on README.rst
> +    datalogistik <generate|cache|validate>
Agreed; looks like you'll need to update the whole README again

2022-08-17 15:36 UTC, austin3dickey requested changes
README

2022-08-18 11:19 UTC, joosthooz commented
Sorry for forgetting the README again.
@jonkeane, validate is always performed if the repo file contains a file listing (with md5sums) for the downloaded dataset. But the location of that check was a bit strange (in `write_metadata()`), so I moved it to `download_dataset()` now.
I split the --validate option into --validate, that only reports if datasets are invalid, and --prune-invalid, that also deletes them.

2022-08-18 15:56 UTC, austin3dickey commented
>Sorry for forgetting the README again

haha no problem; once we do https://github.com/conbench/datalogistik/issues/25 we could have the docs automatically just print out the help page so we don't have to remember to update the README over and over

2022-08-18 16:10 UTC, austin3dickey approved these changes
I think this makes sense; I'm glad the validation is done upon download. I'm not positive anyone will ever need to use `--prune-invalid` or `--validate`, but if we don't want users to touch the cache directly then it makes sense to provide an approved way to do those things.

2022-08-19 12:08 UTC, merged