WIP Added --link option to create a hardlink to the cache
conbench/datalogistik pull request #40
Opened 2022-08-10 16:02 UTC by joosthooz

Not working yet

2022-08-11 14:46 UTC, joosthooz commented
This PR also needs to deal with file permissions, and don't overlook the issue of file permissions when cleaning/pruning cache entries.

2022-08-16 14:46 UTC, alistaire47 approved these changes
I like this! It makes lots of sense as scale factor gets big. Should linking or `--bypass-cache` be the default so as to control disk usage? As far as I can think of all our use-cases are read-only.

2022-08-16 15:31 UTC, joosthooz commented
Yes we should consider that! Right now linking is probably better because at this moment the cache bypass option just deletes the cache entry after it finishes the copy (but that means it does consume twice the storage during the process).

2022-08-16 15:33 UTC, joosthooz commented
BTW, should I explicitly set permissions again after copying/hardlinking?

2022-08-17 16:02 UTC, austin3dickey requested changes
Looks good! A handful of things.

>should I explicitly set permissions again after copying/hardlinking?

I don't think that's necessary; both ways you're calling `shutil.copytree()` preserve permission bits.

2022-08-18 12:28 UTC, joosthooz commented on datalogistik/util.py
> +    # TODO: Deal with having multiple files in a single compressed archive
#47

2022-08-18 12:31 UTC, joosthooz commented on datalogistik/util.py
> +        os.chmod(path, 0o555)
That command is supposed to be for the directories. They need exec perms to allow listing the dir contents.
I'll fix it, thanks for spotting.

2022-08-18 12:38 UTC, joosthooz commented on datalogistik/datalogistik.py
> +            if argument_info.scale_factor and argument_info.scale_factor != "":
Thanks, done in [4c0f555](https://github.com/conbench/datalogistik/pull/42/commits/4c0f55543d61ab5250882db79925260bcc73604b)
(and merged, I need this fix...)

2022-08-18 12:39 UTC, joosthooz commented on datalogistik/util.py
> +    for filename in filenames:
Probably it should have been indented!

2022-08-18 12:42 UTC, joosthooz commented on datalogistik/cli.py
> +        action="store_true",
I've made it the default, and changed the option to `--make-copy`

2022-08-18 12:42 UTC, joosthooz commented
I've made hard-linking the default, and changed the option to `--make-copy`

2022-08-18 12:43 UTC, joosthooz commented on datalogistik/util.py
> +def set_readonly(path):
Done

2022-08-18 12:43 UTC, joosthooz commented on datalogistik/util.py
> +    for filename in filenames:
ok done

2022-08-18 12:43 UTC, joosthooz commented on datalogistik/util.py
> +        os.chmod(path, 0o555)
ok done

2022-08-18 12:43 UTC, joosthooz commented on README.rst
> +``link``
Done (with new option name

2022-08-18 15:57 UTC, joosthooz commented
I added an option to specify the path of the output. This way, users can add all of the hierarchy levels they want. How do you feel about that @alistaire47 @austin3dickey ?

2022-08-18 16:28 UTC, austin3dickey requested changes
looks good! Just one thing

2022-08-18 16:28 UTC, austin3dickey commented on datalogistik/datalogistik.py
> +            output_dir = pathlib.Path(argument_info.output, argument_info.dataset)
I wonder if we should just take the given output dir literally instead of creating a subfolder with the dataset name?
```suggestion
            output_dir = pathlib.Path(argument_info.output)
```

2022-08-18 16:28 UTC, austin3dickey commented on datalogistik/datalogistik.py
> +            output_dir = pathlib.Path(argument_info.output, argument_info.dataset)
oh if you think that's a good idea you'll have to change it down below too

2022-08-18 16:40 UTC, alistaire47 commented
> I added an option to specify the path of the output. This way, users can add all of the hierarchy levels they want. How do you feel about that @alistaire47 @austin3dickey ?

That solves my problem, thanks! And it should scale well should we need to stick chunk size or whatever in there down the line. Questions:

- Will it create directories if they don't exist? Or only the last level? E.g. by default it will create `tpc-h`; if I pass `-o tpc-h/parquet/compression=snappy/sf=1000` do I need to create any dirs?
- For non-TPC-H datasets that are a single file, will it still always create a dir? Do users pass a path to a dir or a file in that case?

2022-08-18 17:30 UTC, austin3dickey commented
@alistaire47 I just tried it out on this branch. In an empty directory, after running `datalogistik generate -d type_floats -f parquet -o some/output/dir` I got:
```
.
├── datalogistik_cache
│   └── type_floats
│       └── parquet
│           └── partitioning_0
│               ├── datalogistik_metadata.ini
│               └── type_floats.parquet
└── some
    └── output
        └── dir
            └── type_floats
                ├── datalogistik_metadata.ini
                └── type_floats.parquet
```
So yes and yes. The directory is necessary because of the metadata file.

My suggestion in my latest review is to remove the `type_floats` between the `dir` and the parquet file. Otherwise, with your example, we're going to end up with something funny like `tpc-h/parquet/compression=snappy/sf=1000/tpc-h/*`.

2022-08-19 07:43 UTC, joosthooz commented
I added the toplevel directory because of the metadata file. If a user would create multiple datasets in a directory, the metadata file would be overwritten! But what I can do is add a check and produce an error if the specified dir already contains a metadatafile (and thus a valid dataset instance).

2022-08-19 11:41 UTC, joosthooz commented
Now the code first checks if the output dir is empty, otherwise is produces an error.

2022-08-19 11:41 UTC, joosthooz commented on datalogistik/datalogistik.py
> +            output_dir = pathlib.Path(argument_info.output, argument_info.dataset)
Now no longer creating a subfolder with the dataset name.

2022-08-19 14:25 UTC, jonkeane commented on datalogistik/util.py
> +            set_readonly(os.path.join(dirpath, filename))
I wonder if we might want to make these optional (or, really, wrap them in a `try`/`catch` and then only warn if they fail)? That way the whole thing won't stop working if it's run on a system that doesn't work (well) with `os.chmod`.

2022-08-19 14:30 UTC, jonkeane reviewed
I've made a few small comments, but a few things I noticed when reading through this:


1. It looks like the file permissions bits are technically separate from the linking bits. It's totally ok to ship those together, but want to make sure I'm not missing something that ties them together necesarily.
1. How do we expect or want folks to use the `OUTPUT` option? Is that the location of the cache generally? If so, we probably want that set by an envvar rather than having to constantly add it to our calls. Or am I misunderstanding what it's used for?
1. This functionality looks pretty complicated + finicky. Do we have tests that cover all of this? And should we add new tests for this new functionality?

2022-08-19 16:36 UTC, alistaire47 commented
> 2\. How do we expect or want folks to use the `OUTPUT` option? Is that the location of the cache generally? If so, we probably want that set by an envvar rather than having to constantly add it to our calls. Or am I misunderstanding what it's used for?

If I understand correctly, this isn't for the cache, it's for the dataset the user is supposed to use. I want to use this to set paths with various disambiguating metadata (e.g. `-o tpc-h/format=parquet/compression=snappy/sf=10/`) when calling from arrowbench and voltrondata-labs/benchmarks.

> I added the toplevel directory because of the metadata file. If a user would create multiple datasets in a directory, the metadata file would be overwritten! But what I can do is add a check and produce an error if the specified dir already contains a metadatafile (and thus a valid dataset instance).

Can this not fail if it would recreate the same dataset, i.e. if the metadata file is the same as what would be written? We're going to be calling this programmatically a lot, and it's easier to just always call it than to check if the dataset exists already (and is really the dataset we want) and call it conditionally. 

Or blow it away and rewrite it? Maybe only if a flag is set, though. Generally a bias for blowing away data not in the cache  (i.e. blowing away the `temp` dir in arrowbench/benchmarks-land) has been a good thing that prevents problems.

2022-08-19 17:34 UTC, jonkeane commented
> If I understand correctly, this isn't for the cache, it's for the dataset the user is supposed to use. I want to use this to set paths with various disambiguating metadata (e.g. -o tpc-h/format=parquet/compression=snappy/sf=10/) when calling from arrowbench and voltrondata-labs/benchmarks.

Hmmm, shouldn't this be part of datalogistik's job do maintain + know about? IMO datalogistik should manage paths and things like this so that the calls from arrowbench, voltrondata-labs/benchmarks, etc. all just need to request a specific dataset (specified by name, compression, format, etc.) and datalogistik returns a file path (ideally out of the cache, but if it hasn't been requested before, it DLs or creates it and then transforms it as needed). That way when we ask for the same dataset from both, the second time we request the file there's 0 work that needs to be done (just the path to the file that the other one already created | used). In an ideal world, the runners have no idea about the cache, how it's managed, etc. they just know how to ask for a specific dataset, and then receive a path to that file to use. Then it's all on datalogistik to ensure we don't have to double-download or double-convert the data we might already have available. 


> Can this not fail if it would recreate the same dataset, i.e. if the metadata file is the same as what would be written? We're going to be calling this programmatically a lot, and it's easier to just always call it than to check if the dataset exists already (and is really the dataset we want) and call it conditionally.
> 
> Or blow it away and rewrite it? Maybe only if a flag is set, though. Generally a bias for blowing away data not in the cache (i.e. blowing away the temp dir in arrowbench/benchmarks-land) has been a good thing that prevents problems.

Definitely agreed that generally speaking the UX (for the programmatic calls) should be: the runner requests a dataset of some sort, and datalogistik ensures that it is available + replies with it's location once it is available. the runners shouldn't ever need to manage the state of the cache (or, possibly even know that there is a cache or that the cache could have state). 

Also blowing away the cache with a flag is good, but probably shouldn't be the default (we want this to make it be easy + cheap to run things if the data already exists, especially for things like TPC-H with large SF, or the taxi dataset). But having the ability to set an external flag once that says "actually, this one time I want you to clean it out" would be nice so that we could "just" schedule a run that does that if we need to and not need to log in to a system somewhere. But I would say let's make an issue for adding that cache clearing later and think about it more concretely + work out what that UX actually looks like once we have datalogistik connected up to things and actually using it.

2022-08-19 19:45 UTC, joosthooz commented
Hi,
- Setting the permissions doesn't have ties to the linking per se, but I feel it is very important to set them when hardlinking, because if a user modifies files that were hardlinked to an entry in the cache, those files will also change so the cache entry will become invalid!
- The way datalogistik works right now is by keeping a cache directory somewhere hidden from the user (I'm moving it into the user's homedrive in #48). If a user requests a dataset, it will provide an output path where it should be created. Or else it will be created in the current working dir. If the dataset in found in the cache, the created files will be hardlinks to the cache entry after this PR is merged. There is an option to use the old behavior, which is just to create a full copy. That way, users can still create an instance that can be written to/modified.

2022-08-19 20:01 UTC, austin3dickey commented
Here's my understanding of what `datalogistik` will do, as this PR stands:
1. User says "I want D dataset with X,Y,Z options"
2. datalogistik gets D and stores it in its secret little cache somewhere
3. datalogistik "returns" it to the user by putting it either in
  a. `./D/*`
  b. `some/requested/path/*`
(And either way, this is secretly a hardlink to the cache, so there's no copying!)
4. If user requests D again, datalogistik will "return" a hardlink to the cache again without redownloading/regenerating

The reason we might want (3b) is in case we have multiple requests for D with different options. Then the user can choose where to put those different files.

This strategy keeps the desirable properties of
- the second time we request the file there's 0 work that needs to be done
- the runners have no idea about the cache, how it's managed, etc
- we can have another option for cleaning the cache if we want

The only downside is that if runners want both `type_floats_csv` and `type_floats_parquet`, they need to use (3b) to request 2 different output paths. Or else the default behavior would put them both in `./type_floats/*`. But I'm tentatively on the side of "that's worth it". Because the other strategy is "datalogistik always generates an output path for you (whether that be a UUID or otherwise-disambiguated path) and you have to figure out how to read that path from stdout." I think that might be a little messier to put on the user.

2022-08-19 20:03 UTC, jonkeane commented
> Setting the permissions doesn't have ties to the linking per se, but I feel it is very important to set them when hardlinking, because if a user modifies files that were hardlinked to an entry in the cache, those files will also change so the cache entry will become invalid!

Awesome, yeah it totally makes sense and adding it here is fine, just wanted to make sure I wasn't missing something that related them...

> The way datalogistik works right now is by keeping a cache directory somewhere hidden from the user (I'm moving it into the user's homedrive in https://github.com/conbench/datalogistik/pull/48). If a user requests a dataset, it will provide an output path where it should be created. Or else it will be created in the current working dir. If the dataset in found in the cache, the created files will be hardlinks to the cache entry after this PR is merged. There is an option to use the old behavior, which is just to create a full copy. That way, users can still create an instance that can be written to/modified.

I think this is a bit more complicated than we need right now. It should simplify things considerably if the datalogistik cache were in one place, and that was the only place that datasets were (i.e. it's not possible to save a dataset elsewhere), and what datalogistik does when requesting a dataset (variant) is gives the caller the path.

We would probably want something like that ability to set a path to use as the cache for datalogistik as an environment variable so that we could ensure it was in a specific directory if we needed to (like our benchmarks version has: https://github.com/voltrondata-labs/benchmarks/blob/86c93f316ca10947044ee4f95475e51b26120963/benchmarks/_sources.py#L14 ). But outside of that let's leave putting data in other directories or locations as a todo if we find that is absolutely necessary. 

I think this will both: simplify our interface for datalogistik but also help us keep concerns separated between the runners and datalogistik. Datalogistik manages getting a particular set of data ready + points to it's location and it is entirely an internal concern to datalogistik where|how|why it does that and then the runners all only know that they can call datalogistik to prepare a specific set of data, and it is provided a path to that data by datalogistik. 

How does that sound?

2022-08-19 20:08 UTC, austin3dickey commented
Yeah the central question is "how can a CLI return a directory". Either it prints out a path to one using stdout that the user parses, or it puts one in a mutually-agreed-upon place that the user knows. I sort of like the latter better as a user, though the former might be more futureproof.

2022-08-19 20:19 UTC, joosthooz commented
> Yeah the central question is "how can a CLI return a directory". Either it prints out a path to one using stdout that the user parses, or it puts one in a mutually-agreed-upon place that the user knows

Exactly, and in this case the path is really complicated for a mutually agreed thing.
So far I've always viewed the cache as something separate also for devs using the tool locally, they might sometimes generate a bunch of TPC-H datasets and other times download some parquet files from S3, and in that case they can manually choose where to place them together so their workspaces don't get clogged.
It's not that much work to change this but for example some of the options wouldn't make sense anymore, like cache bypass, and the difference between a copy and hard-linking (as we're dealing with in this PR) would no longer exist because the result is just a pointer to the entry in the cache itself.

2022-08-22 12:27 UTC, jonkeane commented
> Yeah the central question is "how can a CLI return a directory". Either it prints out a path to one using stdout that the user parses, or it puts one in a mutually-agreed-upon place that the user knows. I sort of like the latter better as a user, though the former might be more futureproof.

_nods_ for the first bit: yeah we will have to take the output and parse it somehow. There are a bunch of ways we can make that happen: pure text, json, etc. But this is the bare minimum integration point that we will need regardless. As for mutually-agreed-upon place: I would strongly advocate for starting off there the most configuration we allow by programs that use datalogistik is that you can tell datalogistik where to put the cache directory, but no more fine-grained than that: you can't tell it the directory structure to use, you can't tell it where to put individual files, etc. This way as we integrate it into our pipelines, we only need to make the call + parsing bit. We don't _also_ have to copy in a bunch of logic about managing file locations.

> Exactly, and in this case the path is really complicated for a mutually agreed thing.
So far I've always viewed the cache as something separate also for devs using the tool locally, they might sometimes generate a bunch of TPC-H datasets and other times download some parquet files from S3, and in that case they can manually choose where to place them together so their workspaces don't get clogged.
It's not that much work to change this but for example some of the options wouldn't make sense anymore, like cache bypass, and the difference between a copy and hard-linking (as we're dealing with in this PR) would no longer exist because the result is just a pointer to the entry in the cache itself.

"the path is really complicated for a mutually agreed thing" this is the part I'm really hoping that datalogistik will allow us to ignore (or, really, solve in one place — inside of datalogistik — and then not have to think about it again). 

"the cache as something separate also for devs using the tool locally" A few things: I think we should concentrate at first at making the experience of using datalogistik in the tools we are building really great + easy. That's its first most important job. We might eventually want a more direct user interface, but let's wait until we get there before we make decisions like "do we want someone to be able to manually manage their cache" and things like that. But even regardless of this, we *do not* want the programmatic use cases of datalogistik to use these ever (or else we loose many of the benefits of datalogistik).

"... some of the options wouldn't make sense anymore ..." Totally agreed, I suspect that we might be building a bit too many of these right now and some of them might make sense for other uses, but aren't directly helping us get datalogistik to the point where it can replace the code in arrowbench, benchmarks, and other places where we have this code repeated. For these, I would say let's make issues that we can come back to with ideas about how some of these fancier options might work for making the interactive experience better, and we can come back to them when we have more info about what that experience should be like.

I do very much believe that getting datalogistik into a place where it replaces all of our bespoke copies of this same code easily + well will make it so that we will need to consider some of these options. But they aren't necessary for this first stage, so we should defer them for now, make sure we land the first stage really well, and then come back to them when we need to.

2022-08-22 15:11 UTC, austin3dickey commented
>But [parsing stdout] is the bare minimum integration point that we will need regardless.

Yep, if our hypothesis is "parsing stdout is an acceptable way to interact with this CLI" then I agree that that should be the primary integration point. If that's an option, then it doesn't make sense to support the "mutually-agreed path" option, because that just adds unnecessary complexity.

As you all said, this will mean a big change to the UI of the package, including:
- No longer creating an "output directory;" only putting files in the cache
- Formalizing what the output string looks like and printing it via stdout
- Hiding the DEBUG and INFO logs by default so it's easier to parse stdout
- Removing the `--bypass-cache` option
- (perhaps more controversially) Removing all the `datalogistik cache` options for now until we have more information about what people need

I'm in favor of these changes. Maybe this PR should be repurposed for those?

2022-08-22 15:25 UTC, jonkeane commented
> Yep, if our hypothesis is "parsing stdout is an acceptable way to interact with this CLI" then I agree that that should be the primary integration point.

Do we have any other ideas or options? IMO this is a minimal first step and we can grow from there if we need to. I don't want to cut off any other possibilities if people have other ideas, of course!

> As you all said, this will mean a big change to the UI of the package, including:
> ...
> I'm in favor of these changes. Maybe this PR should be repurposed for those?  

Yeah, I would also be in favor of pulling back | pulling these out for now and get the minimal version working where only datalogistik knows how to deal with its own cache and it only ever replies with paths. And then like you say, once we get more information about how interactive use might work, we can work to add (or expose) those features

2022-08-22 15:39 UTC, austin3dickey commented
>Do we have any other ideas or options? IMO this is a minimal first step

This is definitely the easiest and safest solution for now. I'm thinking "how do other CLIs work?" and it's either 1) there's a side effect that you have to Just Know™ how to deal with, 2) you parse a string (like running `curl https://... | my_prog`), or 3) there are a bunch of language bindings (httr, requests).

Going with 2 seems like a good fit for this package.

2022-08-22 17:24 UTC, joosthooz commented
These changes are relatively simple I think. The `copy_from_cache` function is tiny and we can just remove it, the cache functions can probably stay (it will still be valuable to validate and prune entries), but maybe we want to change the naming.
Yeah all the debug/info/etc output will need to be removed or at the very least redirected to stderr.

2022-09-05 10:25 UTC, merged