Add functionality to specify schema
conbench/datalogistik pull request #41
Opened 2022-08-11 15:26 UTC by joosthooz

Instead of relying on pyarrow.dataset, we would like to be able to specify a schema in the repo file. This will help solve type problems in large files, because pyarrow.dataset only inspects the first 1MB of data to infer types of columns.

2022-08-12 09:14 UTC, joosthooz commented
>We might need to go a little deeper than that for fields with options, e.g. unit/timezone for timestamps and precision/scale for decimal. Maybe just optional kwargs that can be passed through like

{
  "id": {"type_name": "string"},
  "click_ts": {"type_name": "timestamp", "type_args": {"unit": "ms"}},
  "some_value": {"type_name": "decimal128", "type_args": {"precision": 7, "index": 3}},
  ...
}
Or flat or otherwise—I don't really care about arrangement, just that it's flexible enough when we need it

2022-08-12 14:47 UTC, joosthooz commented
This code has the basic functionality and is able to convert the fanniemae dataset. It can't handle datatypes with parameters yet.

2022-08-12 15:16 UTC, edponce commented
Out of curiosity, are there files/datasets where 1MB has not been enough to resolve its schema? I ask because this can be an improvement that Arrow will benefit as well.

2022-08-12 16:06 UTC, alistaire47 commented
> Out of curiosity, are there files/datasets where 1MB has not been enough to resolve its schema? I ask because this can be an improvement that Arrow will benefit as well.

They definitely exist, and there's no magic number here; at some point you just have to specify a schema. An example is an export from a database table sorted by timestamp where a nullable field was added at some point—values may be entirely null for millions+ of observations even though there's useful data at the end of the dataset.

Especially for interactive work, being able to specify a partial schema just for columns you know are screwy can be handy; [readr::cols()](https://readr.tidyverse.org/reference/cols.html) takes this approach with a default of inferring types for unspecified columns. Obviously specifying a complete schema is _better_, but forcing users to do so can lead to other antipatterns. What we have is good, just maybe a little idealistic.

2022-08-12 16:18 UTC, edponce commented
@alistaire47 Thank you for the explanation. A possible solution for file format standardization is to include metadata with a value per column identifying where the first non-null value appears, this way tools can fetch the value directly for schema resolution.

2022-08-12 16:30 UTC, alistaire47 commented
> A possible solution for file format standardization is to include metadata with a value per column identifying where the first non-null value appears, this way tools can fetch the value directly for schema resolution.

@edponce Ooh that would be great, and handle a lot of problem cases! The remaining issues I've run into have all been in regards to schema params of fields that are difficult to infer from data, e.g. unit/timezone for timestamps. I think at least timestamp unit handling may be improved (i.e. they roundtrip file <-> memory correctly with defaults) in more recent parquet versions, though?

2022-08-15 11:36 UTC, joosthooz commented
@edponce thanks for contributing to the discussion! Suppose you go through the trouble of storing the row number where the first value is encountered, wouldn't it be just as much work to simply store the datatype of the column?

2022-08-15 11:40 UTC, joosthooz commented
(Related JIRA BTW: https://issues.apache.org/jira/browse/ARROW-8221)

2022-08-15 17:40 UTC, edponce commented
@joosthooz yeah, you are right. There are many variations data details can be provided to help with schema resolution. In an ideal world, most data formats in file/memory would have metadata (min, max, null count, nrows, ncols, types, etc) and consistent across formats.

Another issue which seems more related to this PR's work, revolves on how to handle data updates? Viewing data as a data structure that can be modified directly creates many issues. If datasets would only be allowed to be modified via some sort of API, then metadata could be updated accordingly during data updates.

BTW, this is just me thinking out loud. Thanks for the discussion!

2022-08-16 16:02 UTC, jonkeane commented
Is it possible to have this PR be based on main instead of the validation branch? I know they might be inter-related in a way that's hard to tease them apart, but it would make reviewing much easier if I could see what the changes are here for schemas and not the validation bits

2022-08-18 15:44 UTC, joosthooz commented
@jonkeane I changed the target branch to the validation branch, so now you only see the additional changes specific to this task. That should help. Once we merge #34 we can change the target branch back to main.

2022-08-18 17:59 UTC, austin3dickey requested changes
nice, this is looking good!

2022-08-18 17:59 UTC, austin3dickey commented on datalogistik/util.py
> +        if new_format == csv:
```suggestion
        if new_format == "csv":
```

2022-08-18 17:59 UTC, austin3dickey commented on datalogistik/util.py
> +                        )  # TODO: does this really always preserve ordering?
How will you verify this TODO? It looks to me like it will always preserve ordering

2022-08-19 17:22 UTC, jonkeane requested changes
Thanks for this, this is looking good. I've commented a few places about the validation code that seems to be in here, though I think that code isn't actually intended to be here or be merged in this PR (a rebase might help, or possibly even pulling those commits out totally?).

We should definitely add some more tests in that check various conversion possibilities (and now might be a good time to setup a general smallish dataset we use in our tests generally speaking that contains all or many of the types we expect to see)

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/cli.py
> +            )
Did anything in here change other than the indent? I don't think so, but the diff isn't particularly easy to tell

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/cli.py
> +        raise RuntimeError(msg)
Same here? If there are changes, maybe highlighting them with a comment describing might be helpful

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/util.py
> +        raise RuntimeError(msg)
I might be misremembering, but I feel like I've seen similar sets of code a few places for confirming that something is a path in the cache. I wonder if we should factor these out to helper utilities that we can call?

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/util.py
> +    return None
Would you mind adding some tests for this function? I find it super helpful to read through for things like this to get a better idea of what this is trying to do + what the defensiveness in it is trying to prevent

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/util.py
> +    # and whether they are optional
How is the optionality specified? I don't think I see anything about optionality below, but I must be missing it?

2022-08-19 17:22 UTC, jonkeane commented on datalogistik/util.py
> +        ro = csv.ReadOptions()  # autogenerate_column_names=True)
Could you expand on this comment here? I'm not totally sure what it's intending

2022-08-19 17:22 UTC, jonkeane commented on tests/test_datalogistik.py
> +    pydict = {"int": [1, 2], "str": ["a", "b"]}
Would it be helpful to have a dataset with one of each type of class and reuse that in tests like this?

2022-08-19 17:22 UTC, jonkeane commented on tests/test_datalogistik.py
> +    util.prune_cache_entry("test_parquet")
I'm not sure if this test does this (it doesn't look like it does, but maybe I'm missing something!), but could we add a test of the actual roundtrip and actually converting schema types? 

It would be good to capture: changing things like int32 to float, int32 to int64, a numeric of some sort to a string, etc. Ideally we would have tests for all of them to confirm that they really do all work (though this should fall into pyarrow pretty quickly, so maybe we don't need total coverage, but at least a decent amount of coverage to have confidence we can do what we say we do would be good)

2022-08-19 19:04 UTC, joosthooz commented
It seems I need to rebase this, I thought retargeting to the main branch after merging #34 would fix it but it didn't.
Thanks for all the comments, especially for all the ideas for tests :+1:

2022-08-19 19:13 UTC, joosthooz commented on datalogistik/util.py
> +        if new_format == csv:
Thanks for catching this!

2022-08-19 19:16 UTC, joosthooz commented on datalogistik/util.py
> +    # and whether they are optional
I removed the comment

2022-08-19 19:30 UTC, joosthooz commented on datalogistik/util.py
> +        ro = csv.ReadOptions()  # autogenerate_column_names=True)
I created a TODO in the code here, and also opened an issue about this: https://github.com/conbench/datalogistik/issues/50

2022-08-19 19:38 UTC, joosthooz commented on datalogistik/util.py
> +                        )  # TODO: does this really always preserve ordering?
I don't know, it's just that if it didn't, it would become a really unpleasant bug!

2022-08-19 19:39 UTC, joosthooz commented on README.rst
> +    datalogistik <generate|cache|validate>
This is outdated code

2022-08-19 19:39 UTC, joosthooz commented on datalogistik/cli.py
> +    )
Also outdated

2022-08-19 19:39 UTC, joosthooz commented on datalogistik/cli.py
> +            )
Also outdated

2022-08-19 19:39 UTC, joosthooz commented on datalogistik/cli.py
> +        raise RuntimeError(msg)
Also outdated

2022-08-19 19:40 UTC, joosthooz commented
Ok things should be up to date again, I'll get started on the recommendations

2022-08-25 14:00 UTC, joosthooz commented on tests/test_datalogistik.py
> +    util.prune_cache_entry("test_parquet")
This functionality is not supported yet, and I think it falls outside the scope of the PR. Even though the code for this might even be rather simple, how to interface this to the user will be a challenge! Created a new issue: https://github.com/conbench/datalogistik/issues/58

2022-08-26 06:38 UTC, joosthooz commented on datalogistik/util.py
> +    return None
I added tests for these new functions

2022-08-30 15:31 UTC, alistaire47 commented on datalogistik/util.py
> +        # or allow a fall-back to read_csv in case schema detection fails?
We've got both csv datasets with no headers (fanniemae) and with headers (nyctaxi). If we're specifying a schema, we should use the names specified there. If we're not...well, we probably should be

2022-08-30 15:33 UTC, alistaire47 commented on datalogistik/util.py
> +        # or allow a fall-back to read_csv in case schema detection fails?
But we should be careful not to accidentally skip the first line if there are no headers and we overwrite ones inferred from the first line of data; we need to store metadata about this for each dataset

2022-08-30 17:48 UTC, austin3dickey approved these changes
This is looking great, especially all these comprehensive tests! Just a few small things.

2022-08-30 17:48 UTC, austin3dickey commented on datalogistik/util.py
> +    return type_name
nit: you could reduce some complexity here!
```suggestion
    return aliases.get(type_name, default=type_name)
```

2022-08-30 17:48 UTC, austin3dickey commented on datalogistik/util.py
> +        return None
nit: maybe log after we've checked for null input?
```suggestion
    if input_schema is None:
        return None
    log.debug("Converting schema to pyarrow.schema...")
```

2022-08-30 17:48 UTC, austin3dickey commented on tests/test_datalogistik.py
> +complete_csv_schema_json_output = "{'a': 'null', 'b': 'bool', 'c': 'int8', 'd': 'int16', 'e': 'int32', 'f': 'int64', 'g': 'uint8', 'h': 'uint16', 'i': 'uint32', 'j': 'uint64', 'l': 'float', 'm': 'dou
Could you please break this long line up? I like this method but you can do whatever works for you:
```
complete_csv_schema_json_output = (
    "string "
    "parts"
)
```

2022-08-31 12:57 UTC, joosthooz commented on datalogistik/util.py
> +    return type_name
Thanks! much better

2022-08-31 12:57 UTC, joosthooz commented on datalogistik/util.py
> +        return None
Done

2022-08-31 12:58 UTC, joosthooz commented on tests/test_datalogistik.py
> +complete_csv_schema_json_output = "{'a': 'null', 'b': 'bool', 'c': 'int8', 'd': 'int16', 'e': 'int32', 'f': 'int64', 'g': 'uint8', 'h': 'uint16', 'i': 'uint32', 'j': 'uint64', 'l': 'float', 'm': 'dou
Done. Thanks for pointing it out, I didn't think of this

2022-08-31 16:33 UTC, alistaire47 approved these changes
A couple nits, but this looks really good!

2022-08-31 16:33 UTC, alistaire47 commented on datalogistik/util.py
> +    return output_schema
This is super useful. Do we have the reverse (serialize a schema to json) here somewhere as well? (Not sure if it's necessary here at the moment, but I've run into cases where it would've been very handy.) It might be nice to put all this schema stuff in a separate file so when I, um, borrow this code in the future it's in a nice self-contained package.

2022-08-31 16:33 UTC, alistaire47 commented on datalogistik/util.py
> +# Convert the given dict to a pyarrow.schema
If we make all these comments into docstrings they'll pop up nicely for us in editors

2022-08-31 16:33 UTC, alistaire47 commented on datalogistik/util.py
> +                    coerce_timestamps="us",
If you've upgraded to arrow 9.0.0, this may be unnecessary now; some of the weird behavior around this was part of the old parquet versions, and the default version got bumped with 9.0.0. Fine to leave here for safety though.

2022-09-01 09:53 UTC, joosthooz commented on datalogistik/util.py
> +    return output_schema
I know, that would be really handy and the `inferred-schema` was actually a workaround for not having it at first (but then after thinking about it I think it is good to know the difference between a user-specified schema vs an inferred one).
The other way is more difficult, though. It might come down to a large case statement with all the types with parameters. I remember seeing some Rust code for this at some point, maybe in datafusion, but I couldn't find it anymore.
Let's implement this in the near future.

Side comment; I found this old spec for Arrow Schema JSON representation: https://github.com/apache/arrow/pull/158/files

2022-09-01 09:54 UTC, joosthooz commented on datalogistik/util.py
> +# Convert the given dict to a pyarrow.schema
Yeah I shouldv'e done that properly from the start. Maybe we should start a PR that does that and adds type hints.

2022-09-01 09:55 UTC, joosthooz commented on datalogistik/util.py
> +# Convert the given dict to a pyarrow.schema
https://github.com/conbench/datalogistik/issues/59

2022-09-01 09:56 UTC, merged