Fixed path creation for cache lookup for other formats
conbench/datalogistik pull request #42
Opened 2022-08-12 10:10 UTC by joosthooz

Updated path creation to reflect https://github.com/conbench/datalogistik/pull/39

2022-08-17 16:16 UTC, austin3dickey requested changes
just one thing

2022-08-17 16:16 UTC, austin3dickey commented on datalogistik/datalogistik.py
> +            if argument_info.scale_factor and argument_info.scale_factor != "":
I didn't realize this was in another PR; check out my comment [here](https://github.com/conbench/datalogistik/pull/40/files#r948129768)

2022-08-18 12:38 UTC, joosthooz commented on datalogistik/datalogistik.py
> +            if argument_info.scale_factor and argument_info.scale_factor != "":
Ah nice, yes, fixed :+1:

2022-08-18 15:30 UTC, austin3dickey approved these changes

2022-08-18 16:11 UTC, merged