Add way to discriminate between parquet compression standards in the cache
conbench/datalogistik pull request #49
Opened 2022-08-19 15:12 UTC by joosthooz

This adds a directory hierarchy level for parquet files, to denote what internal compression is used.
For downloaded files, it first downloads to a directory `parquetcompression_unknown`, then detects the compression and moves it to the proper location in the cache.

2022-08-22 19:07 UTC, austin3dickey reviewed
Looking great!

2022-08-22 19:07 UTC, austin3dickey commented on tests/test_datalogistik.py
> +    )
I assume these tests cover a lot of this new code, correct? Is there value in adding another test that converts between different compression formats?

2022-09-01 14:14 UTC, joosthooz commented
Now both parquet and csv have a cache directory hierarchy level for compression. Conversion between gzip and uncompressed work both ways, but I'm going to change that into re-downloading the file because it is much faster

2022-09-01 16:35 UTC, alistaire47 commented
> Conversion between gzip and uncompressed work both ways, but I'm going to change that into re-downloading the file because it is much faster

This is definitely not true for all datasets; some of the taxi variants can take >1h to download but gzip/decompress in minutes. And why wouldn't we [usually] keep the downloaded version around anyway, since that's the source of truth? Or keep a quick-to-read version around (probably parquet-snappy) so the primary cost is just resaving?

2022-09-01 18:21 UTC, austin3dickey requested changes
Nice, a few small things. I also agree with Ed that we should probably prefer converting a local dataset instead of re-downloading it, even at the cost of speed, because fewer network requests is probably a good idea

2022-09-01 18:21 UTC, austin3dickey commented on datalogistik/cli.py
> +        "for csv: either None of gz)",
```suggestion
        "for csv: either None or gz)",
```

2022-09-01 18:21 UTC, austin3dickey commented on datalogistik/cli.py
> +                opts.compression = "gz"
Should we be using `tar.gz`? I think it's more standard for that to be the file extension, no?

2022-09-01 18:21 UTC, austin3dickey commented on tests/test_datalogistik.py
> +    )
It's hard for me to tell from this file, but did you cover compressing/decompressing csvs and parquets in these tests?

Also, perhaps there's value in adding compression to our integration tests?

2022-09-02 14:56 UTC, joosthooz commented
I added some tests, but there's still a job to be done there; to be able to test all kinds of conversions between format, partitioning, and compression, we first need to generate a dataset with only datatypes that both parquet and csv support. I'll make a note of that

2022-09-06 15:55 UTC, austin3dickey reviewed
I see the unit tests are sometimes failing with
```
Differing items:
{'local-creation-date': '2022-09-05T10:40:14+0000'} != {'local-creation-date': '2022-09-05T10:40:13+0000'}
```
Will that be fixed in #46 or can you fix it here?

2022-09-06 18:29 UTC, joosthooz commented
> Will that be fixed in https://github.com/conbench/datalogistik/pull/46 or can you fix it here?

Yes, it is fixed in #46

2022-09-06 19:23 UTC, austin3dickey approved these changes
LGTM

2022-09-07 08:41 UTC, merged