Add dims to the output result
conbench/datalogistik pull request #87
Opened 2022-09-20 13:13 UTC by joosthooz

Closes #77

2022-09-20 13:14 UTC, jonkeane commented on datalogistik/dataset.py
> +    # until it is, its entries should correspond to the entries in the tables list
💯  dims should be at the table level

2022-09-20 13:16 UTC, joosthooz commented on datalogistik/dataset.py
> +    # until it is, its entries should correspond to the entries in the tables list
And for the output, should we make the table entries more complex or create 2 separate lists that correspond to each other?

2022-09-20 13:18 UTC, jonkeane requested changes
This looks great — agreed with your comment that this should actually be at the table level. Would you mind adding it there in this PR?

2022-09-20 13:31 UTC, jonkeane commented on datalogistik/dataset.py
> +    # until it is, its entries should correspond to the entries in the tables list
Definitely make the table entries more complex. Any downstream consumer will need to iterate through that list anyway, so they will be able to pull stuff out, no reason to have a second one that needs to be iterated through separately

2022-09-21 14:13 UTC, jonkeane approved these changes
Looking good, a few relatively minor comments | suggestions. Thanks!

2022-09-21 14:13 UTC, jonkeane commented on datalogistik/dataset.py
>      # TODO: Post-init validation for things like delim if csv, etc.
```suggestion
```

2022-09-21 14:13 UTC, jonkeane commented on datalogistik/dataset.py
> +            tables[table.table] = table_entry
This is slightly more simple (it also always has `dim` which IMO is good for an API like this since other things will parse this output and then we can always rely on it being there

```suggestion
            tables[table.table] = {
                "dim":  table.dim, # might need if table.dim after this to set to None
                "path": str(self.ensure_table_loc(table))
            }
```

2022-09-21 14:13 UTC, jonkeane commented on datalogistik/dataset.py
> +    def fill_in_nones(self, other_dataset_info):
A small docstring here might be nice to describe what this is doing.

Also, maybe we could call `other_dataset_info` something like `dataset_for_default` or something so it's clear(er) that's where defaults are coming from

2022-09-21 15:54 UTC, merged