Move header line to table
conbench/datalogistik pull request #89
Opened 2022-09-21 10:01 UTC by joosthooz

Move the header_line field to the table class.
Also, now using only underscores in repo file and metadata file properties.

2022-09-21 14:52 UTC, joosthooz commented
This ended up becoming uglier than I had hoped, but it works and addressed the 2 issues.
`ensure_..._loc` always create the path as a dir which is not always what you want, sometimes it will return a path to a file. When converting to a compressed csv, we don't want the compression extension yet, because we need to compress in a separate step after conversion.
Also, the code currently does not detect whether a conversion can be done by just doing a simple (de)compress. It will default to picking a parquet variant if it exists.

2022-09-21 15:36 UTC, jonkeane requested changes
This is looking good, a few comments. 

The biggest one is that we should make sure we're using `ensure_table_loc()` as the central way to get table locations for referencing them. If we are having issues because `ensure_table_loc()` is creating files|directories when we don't want it to, we could make two functions:

`get_table_loc()` and `ensure_table_loc()` and have `ensure_table_loc()` call `get_table_loc()` internally.

2022-09-21 15:48 UTC, joosthooz commented on datalogistik/dataset.py
> -        )
What triggered me to remove it, is that because we moved `header-line` into `Table`, this replace action did not reach it anymore. So then we'd need to do this recursively, and I really didn't like that.

2022-09-21 15:51 UTC, joosthooz commented on datalogistik/dataset.py
> +                        "file_path": table_loc.relative_to(self.ensure_dataset_loc()),
This change is just about consistency with the repo file, for me either is fine but I prefer using the same keyword for both places

2022-09-21 15:53 UTC, joosthooz commented on datalogistik/dataset.py
> +                    ),
We can't, because that will create a directory with the name of the output file, causing an error in some cases. As you noted we should probably create 2 separate functions.

2022-09-21 17:06 UTC, jonkeane commented on datalogistik/dataset.py
> -        )
Ah good point!

2022-09-21 17:07 UTC, jonkeane commented on datalogistik/dataset.py
> +                        "file_path": table_loc.relative_to(self.ensure_dataset_loc()),
Agreed on repo ~= dataset elements. Let's do `rel_path` for both since it's even more important in the repo that people know that path is relative to the URL at the dataset level

2022-09-21 17:09 UTC, jonkeane commented on datalogistik/dataset.py
> +                    ),
Cool, yeah, feel free to move to the two function approach. And when we do we should audit our other uses and make sure we do `ensure_...` when we need to and `get_...` when we need to

2022-09-26 14:33 UTC, jonkeane requested changes
Thanks for this, it's getting closer. 

A few minor comments + a larger suggestion at refactoring some of the filename | extension | path getters

2022-09-26 14:33 UTC, jonkeane commented on datalogistik/dataset.py
>          return name
On second thought, now that I've poked through this code a bit more, this function is used really as more of an extension identifier than it is a filename getter in the one place that it's used. What if we leaned into that more, renamed this  `get_table_extension()` (or possibly, just `get_extension`), had it return the extension there,

And then edited `ensure_table_loc()` to be:

```
    # this function will get the location of a table to be used + passed to a pyarrow dataset. It will ensure that all the directories leading up to the files that contain the data all exist (but will not create the data files themselves, directly). This function should be used to get the location of a table rather than constructing it oneself
    def ensure_table_loc(self, table=None):
        dataset_path = self.ensure_dataset_loc()
        # Defaults to the 0th table, which for single-table datasets is exactly what we want
        table = self.get_one_table(table)

        if len(table.files) > 1 or table.multi_file:
            table_path = pathlib.Path(dataset_path, table.table)
            table_path.mkdir(exist_ok=True)
        elif self.name not in tpc_info.tpc_datasets and table.files:
            # If there is a files entry, use it
            table_path = pathlib.Path(dataset_path, table.files[0]["file_path"])
        else:
            table_path = pathlib.Path(dataset_path, table.table + self.get_extension(self))
        return table_path
``` 

I've added a bit of a docstring too, which we should add to `ensure_table_loc()` regardless of the specifics of the change. We should also use `dataset_path / table.table` instead of `pathlib.Path(dataset_path, table.table)` where we do that in this function.

2022-09-26 14:33 UTC, jonkeane commented on tests/test_dataset.py
> -    assert new_ds.get_table_name(new_ds.tables[0]) == "chi_traffic_sample"
Alternatively: see my comment below about change `get_table_filename()` into an extension helper instead of a filename helper. In which case these tests would be quite a bit different

2022-09-26 16:32 UTC, jonkeane commented on datalogistik/dataset.py
> +                    )
And FTR: here's what happens when I tested this in our integration:

https://github.com/voltrondata-labs/arrowbench/actions/runs/3128761468/jobs/5077008768#step:10:341

```
DEBUG [2022-09-26 15:00:11,610] Cleaning cache directory '/home/runner/.datalogistik_cache/fanniemae_2016Q4/a6a662b'
Traceback (most recent call last):
  File "/opt/pipx_bin/datalogistik", line 8, in <module>
    sys.exit(main())
  File "/opt/pipx/venvs/datalogistik/lib/python3.8/site-packages/datalogistik/datalogistik.py", line 58, in main
    new_dataset = close_match.convert(dataset)
  File "/opt/pipx/venvs/datalogistik/lib/python3.8/site-packages/datalogistik/dataset.py", line 468, in convert
    write_options = dataset_write_format.make_write_options(
  File "pyarrow/_dataset_parquet.pyx", line 183, in pyarrow._dataset_parquet.ParquetFileFormat.make_write_options
  File "pyarrow/_dataset_parquet.pyx", line 516, in pyarrow._dataset_parquet.ParquetFileWriteOptions.update
TypeError: unexpected parquet write option: include_header
/opt/pipx_bin/datalogistik
```

2022-09-27 09:05 UTC, joosthooz commented on datalogistik/dataset.py
> +                        download_path = table_path / pathlib.Path(file_name).name
Absolutely, that was the idea behind this comment. We'd probably get into trouble if these names do not match, but in this case (multi-file) it is crucial the files are in the proper dir so I'm overriding it just to be sure. I've changed the comment a bit, hopefully for the better.

2022-09-27 09:10 UTC, joosthooz commented on datalogistik/dataset.py
> +                probe_file = next(table_loc.iterdir())
`rel_path`: yes, but I also did that change in #97 so I left it like this here.
Comment about `probe_file`: done

2022-09-27 09:15 UTC, joosthooz commented on datalogistik/dataset.py
> +                    nrows = new_table.dim[0]
Ok, 
https://github.com/conbench/datalogistik/issues/98
Please add any additional thoughts about this

2022-09-27 09:27 UTC, joosthooz commented on repo.json
> +                        "url": "https://ursa-qa.s3.amazonaws.com/fanniemae_loanperf/2016Q4.csv.gz",
This code only supports multi-file where each file has it's own url. What your describing is 1 url for downloading multiple files. We can also choose to support that, but then we would need to remove the loop going over all the files and just perform a download command of that 1 url (and then possibly validating all the files that were downloaded).
Do we need to support both cases? That would make the code ugly and would need some careful documentation.

2022-09-27 09:28 UTC, joosthooz commented on testrepo.json
> +[
No, but the datasets are very useful to test downloading multi-table and multi-file datasets.
I could add unit tests for them but maybe these files are a bit large for that?

2022-09-27 09:39 UTC, joosthooz commented on datalogistik/dataset.py
>          return name
Ok, done

2022-09-27 10:01 UTC, joosthooz commented on repo.json
> +                        "url": "https://ursa-qa.s3.amazonaws.com/fanniemae_loanperf/2016Q4.csv.gz",
BTW., `util.download_file("s3://ursa-labs-taxi-data", pathlib.Path("./"))`:
`urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme s3`
It seems this is not supported by urllib3, we need another library to download a bucket directly.

2022-09-27 10:50 UTC, joosthooz commented on datalogistik/dataset.py
> +                    )
Ok, this has been refactored into a function `get_write_format`. Unfortunately, I couldn't add a proper test for it because the writeoptions class cannot perform an equality check (probably due to Cython shenanigans)

2022-09-27 12:54 UTC, joosthooz commented on repo.json
> +                        "url": "https://ursa-qa.s3.amazonaws.com/fanniemae_loanperf/2016Q4.csv.gz",
I reverted the change to `repo.json` and added a check that should support both having a url at dataset level or urls at file level.
And I created a PR off of this branch, that does a first attempt at supporting S3: https://github.com/conbench/datalogistik/pull/99

2022-09-27 13:31 UTC, jonkeane commented on datalogistik/dataset.py
> +                    )
OOOH yes, we should submit a Jira to the arrow tracker for that. But what I did in cases like this is to test individual components that I cared about. It took some feeling around in the docs + a bit of RTFSing to get the exact names right, but here's an example: https://github.com/conbench/datalogistik/blob/fbe34cce794bf164ad68e24dc286b365bc32dc91/tests/test_dataset.py#L348-L351

2022-09-27 13:34 UTC, jonkeane commented on testrepo.json
> +[
Since this PR is already pretty big, let's defer this to a new issue about adding a test repo file + testing it. Agreed it's helpful, we might need to upload some of our sample files if we don't have them already, but they are _much_ smaller.

The other option is we could mock that download function and then use the fixture files themselves. But anyway, there are a bunch of little decisions + things to add to this, so let's make an issue and follow up on that later

2022-09-27 15:00 UTC, joosthooz commented on repo.json
> +                        "url": "https://ursa-qa.s3.amazonaws.com/fanniemae_loanperf/2016Q4.csv.gz",
s3 download support has been added! It's hard to test, though, because the taxi bucket is very large.
I have a slight preference for keeping it as it is in the current state; either the url is on the dataset level, or there is a url entry for each file entry. Because a base url with suffixes is less flexible (what if they're not all in the same dir on the server?)

2022-09-27 18:26 UTC, jonkeane requested changes
Looking good. The one major thing left is to make sure that we can do (raw) csv(.gz) -> csv on our fannie dataset with `header_line: False` and then we can merge this.

I noticed some additions on multi-table datasets added this last set of pushes, IMO we should create a separate PR to do those, there are a bunch of little decisions we'll need to make and getting that right here will mean extending this PR even longer.

2022-09-27 18:26 UTC, jonkeane commented on repo.json
> +                "header_line": false,
:100:

2022-09-27 20:19 UTC, joosthooz commented on repo.json
> +                "table": "2009"
Yes, this is wrong, sorry. I was trying to download only a subset of the bucket but it didn't work.

2022-09-28 14:24 UTC, jonkeane reviewed
A few minor comments, though looks like our integration tests in arrowbench have an issue still: https://github.com/voltrondata-labs/arrowbench/actions/runs/3136784477/jobs/5109925017

2022-09-28 14:24 UTC, jonkeane commented on datalogistik/cli.py
> +            dataset.fill_in_defaults(dataset_from_repo)
Nice way to catch if the dataset isn't in the repo but still go

2022-09-28 14:24 UTC, jonkeane commented on datalogistik/dataset.py
> +            self.cache_location = pathlib.Path(self.cache_location)
We don't currently guard against this, but I believe both `cache_location` and `dir_hash` should be removed before we write jsons to disk. They should only really be needed when writing a dataset for the first time, after that the location and hash is known by where the metadata file is. 

Would you mind writing up an issue with ^^^ that we can tackle later and adding a TODO here that basically says "When we actually guard that those aren't saved, we can remove this"?

2022-09-28 14:24 UTC, jonkeane commented on datalogistik/dataset.py
> +            schema = None
Do we want this here? We don't yet support it, but we will soon support changing schemas, and being able to specify a schema even with parquet is a way to do that. All current datasets in the repo now will be `None` regardless, but I don't think we should hardcode it here too (unless we absolutely have to for some other reason?)

2022-09-28 14:24 UTC, jonkeane commented on datalogistik/dataset.py
> +                delimiter=self.delim if self.delim else ",",
This is fine for now, but would you mind making a TODO that says we should actually set the delim default during init + use `None` (which in pyarrow will default to `","` itself)?

2022-09-28 14:24 UTC, jonkeane commented on datalogistik/dataset.py
> +                    )
Do you need an `os.extsep` here (or whatever the pathlib equivalent of that is?)?

2022-09-28 14:50 UTC, jonkeane commented on datalogistik/dataset.py
> +            table_path = dataset_path / table.files[0]["file_path"]
```suggestion
```

I suspect this is a better way to resolve the filename issue that the last commit is working around. Is there a case where we want to rely on the `file_path` there instead of the table_name + the conventions we've established for those?

2022-09-28 15:52 UTC, joosthooz commented on datalogistik/dataset.py
> +            schema = None
This is just to prevent an error a couple of lines down, when trying to read the parquet dataset, because it doesn't accept a schema argument. Note that this doesn't throw away the schema in the metadata

2022-09-28 15:53 UTC, joosthooz commented on datalogistik/dataset.py
> +                    )
I chose to include that in `get_extension()`

2022-09-28 15:55 UTC, joosthooz commented on datalogistik/dataset.py
> +                delimiter=self.delim if self.delim else ",",
Looking at it a 2nd time now, the whole if seems superfluous, I'll consider removing it. But the real question is then do we want to initialize to `","` ourselves? Even that isn't really necessary considering pyarrow's default behavior.

2022-09-28 16:05 UTC, joosthooz commented on datalogistik/dataset.py
> +            table_path = dataset_path / table.files[0]["file_path"]
You're right, we should never! So it's better to enforce it. The only thing that `file_path` could do is provide a suffix for the download url. But there's an important detail: the download function needs a full path to a file, not a dir. So for multi-file tables, we _need_ a `file_path` entry both for the url suffix and the name of the file in the table dir.

2022-09-28 16:09 UTC, joosthooz commented on datalogistik/dataset.py
> +            table_path = dataset_path / table.files[0]["file_path"]
Done in [5b9be54](https://github.com/conbench/datalogistik/pull/89/commits/5b9be545b113d284d209aa09db84e44c9e138eee)
Note that we still have PRs open for the details of multi-file/multi-table downloads #101 #47

2022-09-28 16:43 UTC, jonkeane approved these changes

2022-09-28 16:58 UTC, merged